# This is a basic workflow to help you get started with Actions
name: 🚀 Deploy website on push

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  web-deploy:
      name: 🎉 Deploy
      runs-on: ubuntu-latest
      steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.cluster029.hosting.ovh.net
          username: tkpripq
          password: ${{ secrets.ftp_password }}
